import type { Product } from "./types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "cerave-foaming-cleanser",
    brand: "CeraVe",
    name: "Foaming Facial Cleanser",
    kind: "cleanser",
    format: "rinse_off",
    activeClasses: [],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "cerave-hydrating-cleanser",
    brand: "CeraVe",
    name: "Hydrating Facial Cleanser",
    kind: "cleanser",
    format: "rinse_off",
    activeClasses: ["hydrator"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "cerave-moisturising-lotion",
    brand: "CeraVe",
    name: "Moisturising Lotion",
    kind: "moisturiser",
    format: "leave_on",
    activeClasses: ["hydrator"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "lrp-toleriane-sensitive",
    brand: "La Roche-Posay",
    name: "Toleriane Sensitive",
    kind: "moisturiser",
    format: "leave_on",
    activeClasses: ["hydrator"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "boj-relief-sun",
    brand: "Beauty of Joseon",
    name: "Relief Sun SPF50+",
    kind: "sunscreen",
    format: "leave_on",
    activeClasses: ["sunscreen"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "lrp-anthelios-uvmune",
    brand: "La Roche-Posay",
    name: "Anthelios UVMune 400 SPF50+",
    kind: "sunscreen",
    format: "leave_on",
    activeClasses: ["sunscreen"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "ordinary-niacinamide",
    brand: "The Ordinary",
    name: "Niacinamide 10% + Zinc 1%",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["niacinamide"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "ordinary-glycolic",
    brand: "The Ordinary",
    name: "Glycolic Acid 7% Exfoliating Toner",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["aha"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "ordinary-salicylic",
    brand: "The Ordinary",
    name: "Salicylic Acid 2% Solution",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["bha"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "ordinary-retinol-05",
    brand: "The Ordinary",
    name: "Retinol 0.5% in Squalane",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["retinoid"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "differin-adapalene",
    brand: "Differin",
    name: "Adapalene Gel 0.1%",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["retinoid"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "ordinary-azelaic",
    brand: "The Ordinary",
    name: "Azelaic Acid Suspension 10%",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["azelaic_acid"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "skinoren-azelaic",
    brand: "Skinoren",
    name: "Azelaic Acid Cream 20%",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["azelaic_acid"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "geek-gorgeous-cglow",
    brand: "Geek & Gorgeous",
    name: "C-Glow 15% Vitamin C Serum",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["vitamin_c_laa"],
    source: "seed_fixture",
    confidence: "fixture",
  },
  {
    id: "cosrx-bha",
    brand: "COSRX",
    name: "BHA Blackhead Power Liquid",
    kind: "treatment",
    format: "leave_on",
    activeClasses: ["bha"],
    source: "seed_fixture",
    confidence: "fixture",
  },
];

export function getProduct(id: string) {
  return SEED_PRODUCTS.find((product) => product.id === id);
}

export function getProducts(ids: string[]) {
  return ids.map(getProduct).filter((product): product is Product => Boolean(product));
}
